spring:
  datasource:
    url: jdbc:h2:mem:h2db
    username: sa
    password:
    driverClassName: org.h2.Driver
    jpa:
      database-platform=org.hibernate.dialect.H2Dialect:
  h2:
    console:
      enabled: true

  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
