spring:
  application:
    name: superheros
    version: 1.0.0
  datasource:
    url: jdbc:h2:mem:h2db
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
